### ISSUE TITLE
factory doesn't pass on authority

### ISSUE THREAD

**Issue by rainbreak** [makerdao/simplecoin#14]
~~need to use delegatecall~~ [no that's not it]

need to `updateAuthority` as well as `updateOwner`

**Comment by rainbeam** [comment]
@nmushegian: am I missing something about authority or does that make sense?

**Comment by nmushegian** [comment]
`need to updateAuthority as well as updateOwner`

it's one or the other, but yeah

edit: the factory returns the Authority as "owned" by sender, while all other contructed contratcs point to authority

**Comment by rainbreak** [comment]
superseded by #8
