### ISSUE TITLE
remove `sensible.sol` in favor of ds-base

### ISSUE THREAD

**Issue by nmushegian** [makerdao/simplecoin#33]

**Comment by nanexcool** [comment]
ds-base does not have a "no-eth" modifier. Is this not necessary anymore with the addition of "payable" to functions?

**Comment by rainbreak** [comment]
@nanexcool: yes, the behaviour changes in solidity >0.4. Now functions must be marked with `payable` if they are to receive Ether, i.e. `noeth` is there by default.

**Comment by gbalabasquer** [comment]
@rainbeam Thanks! We will implement it with the other changes next week.
