### ISSUE TITLE
Admin can not add roles

### ISSUE THREAD

**Issue by gbalabasquer** [makerdao/simplecoin#35]
In the actual contract only the owner of the authority can add roles. Do we want to allow the admins to be able to add other admins, issuers and holders as well? (or maybe just add only issuers and holders but not other admins)

**Comment by nmushegian** [comment]
What about having the authority's owner be itself and having the admin role totally take over the "simplecoin owner" concept? So `admin` role has `setRole` capability etc on the authority itself. This will also address https://github.com/makerdao/simplecoin/issues/36

**Comment by gbalabasquer** [comment]
@nmushegian I would not lose the owner entity. In the end it is the only way to protect who created the coin so none could remove the admin access.

We were thinking of adding the following to the SimpleRoleAuth. So we can allow admins to set roles and also add admin role when the ownership is transferred.

```
function SimpleRoleAuth(address target) {
        // == admin
        //ADD=> setRoleCapability(admin, target, sig("setUserRole(address,uint8,bool)"), true);
        setRoleCapability(admin, target, sig("register(address)"), true);
        setRoleCapability(admin, target, sig("setVault(uint48,address)"), true);
        setRoleCapability(admin, target, sig("setFeed(uint48,uint24)"), true);
        setRoleCapability(admin, target, sig("setSpread(uint48,uint256)"), true);
        setRoleCapability(admin, target, sig("setCeiling(uint48,uint256)"), true);
        setRoleCapability(admin, target, sig("unregister(uint48)"), true);

        // == issuer
        setRoleCapability(issuer, target, sig("issue(uint48,uint256)"), true);
        setRoleCapability(issuer, target, sig("cover(uint48,uint256)"), true);

        // == holder
        setRoleCapability(holder, target, sig("transfer(address,uint256)"), true);
        setRoleCapability(holder, target, sig("transferFrom(address,address,uint256)"), true);
    }

    //ADD=> function setOwner(address newAddress) {
        addAdmin(newAddress);
        super.setOwner(newAddress);
    }
```

**Comment by nmushegian** [comment]
This solution is fine but I don't think it buys much in terms of security - admins still get enough capabilities to ruin the system. But I like it from the point of view of still having a "super admin" more for recovery than anything.

I think we should have all components directly owned by the role-auth as well, and add a function like this to the role authority:

```
function release(DSAuth what, address new_owner)
    auth
{
    what.setOwner(new_owner);
}
```

This should make moving the system around as one piece simpler and I think should be party of the core `DSAuthority` interface.

Thoughts?

**Comment by gbalabasquer** [comment]
But what do you mean by all components owned by the role-auth? Are you referring to make the simplecoin object owned by the authority? What would the functional purpose of that?
Probably we are not understanding well the model.

**Comment by nmushegian** [comment]
This way they can all be moved together.
- If their owners are the auth's owners, then when you update the auth's owner, the old owner can still backdoor the components
- If their owners are 0, reclaiming ownership to hand to an installer contract require several steps (essentially unlocking setOwner via the auth rules)

If 1) components have their owner set to the authority, then 1) is handled implicitly, and 2) is fixed with a `releaseAuthorized` function which would be universally useful to all `DSAuthority` implementations

**Comment by nmushegian** [comment]
I just realized that simplecoin is the only component in this system which could explain the confusion. I think in this case we could even say `Simplecoin is DSRoleAuth` and have it be self-authorized, then there is a clean single owner again

**Comment by gbalabasquer** [comment]
Well probably that is a good way to simplify it.
In this case, if I understanding correctly, the authority object inside the coin would disappear. Then setting the roles and the ownership would be directly against the Simplecoin.
Probably it will take us some time as we will need to change a some tests and the UI, but seems a good way to make it easier.
If you give us the ok, we can plan the changes and send you the pull request to check the contract.
