### ISSUE TITLE
Add a name/label to the coin

### ISSUE THREAD

**Issue by gbalabasquer** [makerdao/simplecoin#38]

**Comment by gbalabasquer** [comment]
Should we do this?

**Comment by nmushegian** [comment]
Maybe replace `rules` with `metadata`? Then you can put whatever fields you want in there.

("Rules" is supposed to be a hash of the actual rules, which shouldn't fit into 32 bytes. So we have to figure that bit out.)

**Comment by dbrock** [comment]
Rename `rules` to `metadata` and change it from `bytes32` to `string`?

**Comment by nmushegian** [comment]
I don't want to encourage storing the whole blob though, I meant we should figure out how we deal with off chain data

**Comment by dbrock** [comment]
Why not?

**Comment by nanexcool** [comment]
@dbrock @nmushegian when you say `metadata` be a `string` you mean we could save it as a JSON string and then parse it in the frontend?

```
{name: "My Simple Stablecoin", sym: "MSS"}
```

etc...?

**Comment by gbalabasquer** [comment]
So any decision taken here?

**Comment by gbalabasquer** [comment]
@dbrock @nmushegian Any resolution here? Should we just change rules to metadata, make it string and save there a json with the different values?
Should also the owner have the ability to edit this field?

**Comment by nmushegian** [comment]
I expect rules to be long enough to be too expensive to put directly. I'd prefer to have `bytes32 metadata_hash`, but we can store a short URL or something similar there for now. We should generally anticipate being able to use content addressed off chain storage for this kind of thing.

**Comment by gbalabasquer** [comment]
Why not to remove rules for now and add these following fields (we noticed some coins are using them and some token registries are using it as a standard):

```
string public name = "";
string public symbol = "";
uint8 public constant decimals = 18;  // 18 decimal places, the same as ETH.
```

Probably the best is to keep the 18 decimals fixed and only give the possibility to complete the name and symbol.
An extra questions would be if those fields could be editable after creating the coin.

**Comment by nmushegian** [comment]
Sounds good to me. I don't think they should be editable and I even think we should enforce 18 decimals at first.
