### ISSUE TITLE
Add event log for issue and cover

### ISSUE THREAD

**Issue by gbalabasquer** [makerdao/simplecoin#39]

**Comment by gbalabasquer** [comment]
We think we can call the same Transfer event of ERC20, but passing the simplecoin address as receiver or sender (depending if it is a cover or an issue).

**Comment by nmushegian** [comment]
Should be careful not to mislead anyone into thinking a transfer to the simplecoin contract would cause a cover.

**Comment by gbalabasquer** [comment]
@nmushegian you are meaning at code level or UI?

Because our idea was to have a history of transactions.
The transactions can be three types: 
- Transfer
- Issue
- Cover

So what we thought was to use always the Transfer event and printing the type depending on the following:
- From and To <> Simplecoin => Transfer
- From == Simplecoin => Cover
- To == Simplecoin => Issue

Other option would be to create two new events: LogIssue and LogCover.

Semantically probably the second option is better but using the same Transfer event has also advantages for the UI programming.

**Comment by nmushegian** [comment]
What advantages does it have?

One one hand there are a lot of tokens that have wacky semantics for transfers so people have to be on guard anyway, but on the other hand there is no reason to add to the confusion by making this token almost totally standard except that it emits `Transfer` on `cover`, but doesn't `cover` on `transfer` in the same context.

**Comment by gbalabasquer** [comment]
The advantage is only in UI where we just call one event filter and brings all the transactions ordered at the same time. But yes makes more sense to create new events for issue and cover and then in the UI combine the three of them to the same table.
