### ISSUE TITLE
use role auth

### ISSUE THREAD

**Issue by nmushegian** [makerdao/simplecoin#8]
https://github.com/nexusdev/ds-roles

TODO:
- [x] implement ds-roles
- [x] update simplecoin implementation
- [x] update readme if necessary

**Comment by nmushegian** [comment]
right now we have three roles, "owner", "issuer", "transferrer"

**Comment by rainbreak** [comment]
For usage of the role contract, is the idea that you compose your own only_role modifer using the inherited functions?

**Comment by nmushegian** [comment]
No, just use `auth`. In the authority, define which capabilities (addresss/sig) belong to which roles, and which addresses have which roles

**Comment by rainbreak** [comment]
blocked by https://github.com/nexusdev/ds-roles/issues/1

**Comment by rainbreak** [comment]
closed by #26
